version: '3.4'
networks:
  local:

services:
  transaction.api:
    image: trasactionapi
    ports:
    - "7000:7000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - local

  init-dynamo-account-table:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name Accounts \
    --attribute-definitions \
    AttributeName=AccountId,AttributeType=S \
    --key-schema \
    AttributeName=AccountId,KeyType=HASH \
    --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb-local:8000"
    depends_on:
      - dynamodb
    networks:
      - local
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1

  init-dynamo-transactions-table:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name AccountTransactions \
    --attribute-definitions \
    AttributeName=AccountId,AttributeType=S \
    --key-schema \
    AttributeName=AccountId,KeyType=HASH \    
    --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb-local:8000"
    depends_on:
      - dynamodb
    networks:
      - local
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1