version: '3.4'

services:
  transaction.api:
    image: trasactionapi
    ports:
    - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dynamoDb

  dynamoDb:
    image: dwmkerr/dynamodb
    command: "-sharedDb"
    hostname: dynamo
    restart: always
    environment:
      - reschedule=on-node-failure
  init-dynamo:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name orders --attribute-definitions AttributeName=id,AttributeType=S AttributeName=customerId,AttributeType=S --key-schema AttributeName=id,KeyType=HASH AttributeName=customerId,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamo:8000"
    links:
      - dynamoDb
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1