version: '3.4'
networks:
  local:

services:
  transaction.api:
    image: trasactionapi
    ports:
    - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - local

  init-dynamo-account-table:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name Accounts \
    --attribute-definitions \
    AttributeName=AccountId,AttributeType=N \
    AttributeName=DocumentNumber,AttributeType=N \
    --key-schema \
    AttributeName=AccountId,KeyType=HASH \
    AttributeName=DocumentNumber,KeyType=RANGE \
    --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb-local:8000"
    depends_on:
      - dynamodb
    networks:
      - local
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1

  init-dynamo-transactions-table:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name Transactions \
    --attribute-definitions \
    AttributeName=TransactionId,AttributeType=N \
    AttributeName=AccountId,AttributeType=N \
    AttributeName=OperationTypeId,AttributeType=N \
    AttributeName=Amount,AttributeType=N \
    AttributeName=EventDate,AttributeType=S \
    --key-schema \
    AttributeName=TransactionId,KeyType=HASH \    
    AttributeName=AccountId,KeyType=RANGE \
    --local-secondary-indexes \
    'IndexName=operationTypeIndex,KeySchema=[{AttributeName=TransactionId,KeyType=HASH}, {AttributeName=OperationTypeId,KeyType=RANGE}], Projection={ProjectionType=ALL}' \
    'IndexName=AmountIndex,KeySchema=[{AttributeName=TransactionId,KeyType=HASH}, {AttributeName=Amount,KeyType=RANGE}], Projection={ProjectionType=ALL}' \
    'IndexName=EventDateIndex,KeySchema=[{AttributeName=TransactionId,KeyType=HASH}, {AttributeName=EventDate,KeyType=RANGE}], Projection={ProjectionType=ALL}' \
    --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb-local:8000"
    depends_on:
      - dynamodb
    networks:
      - local
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1