package com.project.transactionApi.Models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.List;

@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "AccountTransactions")
public class AccountTransaction {
    @DynamoDBHashKey(attributeName = "AccountId")
    @DynamoDBAutoGeneratedKey
    public String accountId;

    @DynamoDBAttribute(attributeName = "Transactions")
    @DynamoDBTypeConvertedJson
    public List<Transaction> transactions;

    public AccountTransaction(){

    }
}
